### ISSUE TITLE
When using the code in Objective C Project, it crashes

### ISSUE THREAD

**Issue by RajChanchal** [lourenco-marinho/ActionButton#1]
When using the code in Objective-C project, it crashes on line number 50: self.parentView = view of ActionButton.swift class. This is how I have implemented:
ActionButtonItem *item = [[ActionButtonItem alloc]initWithTitle:@"New Task" image:nil];
ActionButtonItem *item2 = [[ActionButtonItem alloc]initWithTitle:@"New Event" image:nil]; ActionButtonItem *item3 = [[ActionButtonItem alloc]initWithTitle:@"New Project" image:nil];
ActionButton *actionButton = [[ActionButton alloc]initWithAttachedToView:self.view items:@[item,item2,item3]];

**Comment by lourenco-marinho** [comment]
Hi @RajChanchal,

I will be looking this problem :) but can you provide some more information how to reproduce this error and the stacktrace please?

Thanks!

**Comment by RajChanchal** [comment]
When using the same code in a new Objective-C project, it seemed to work. But it happens in my older project. 
![screen shot 2015-06-19 at 11 22 29 am](https://cloud.githubusercontent.com/assets/7058465/8248203/8f8f15a4-1675-11e5-86fc-c3bddcbc7284.png)

And here is the Assembly of the same point:

![screen shot 2015-06-19 at 11 38 25 am](https://cloud.githubusercontent.com/assets/7058465/8249773/1619a682-1687-11e5-91dd-22bab814057c.png)

**Comment by RajChanchal** [comment]
@lourenco-marinho  And how can this line be converted to Objective-C:
actionButton.action = { button in button.toggleMenu() }

**Comment by lourenco-marinho** [comment]
actionButton.action = ^(ActionButton  *button) { [button toggleMenu]; };

**Comment by lourenco-marinho** [comment]
The problem was that the Deployment Target was set to iOS 7.1... Just updating to iOS 8.0 or higher will solve the problem.

**Comment by RajChanchal** [comment]
Thanks @lourenco-marinho Great control. I'll inform you when the app will be uploaded, so that you can include my app in the list of the apps which may have used your control.

**Comment by lourenco-marinho** [comment]
@RajChanchal that will be great!

Thanks a lot
