### ISSUE TITLE
ActionButton on UITableViewController not working

### ISSUE THREAD

**Issue by Vitalini** [lourenco-marinho/ActionButton#12]
How can fix?
Thanks

**Comment by lourenco-marinho** [comment]
Hi @Vitalini can you provide some more information on your problem?

**Comment by Vitalini** [comment]
Here is an example. UIViewController is working and UITableViewController not.
https://www.dropbox.com/s/5yrir7wsyyu2igd/test.zip?dl=0

**Comment by lourenco-marinho** [comment]
@Vitalini you can't add subviews to UITableViewControllers, try adding the Action Button to another UIVIew

**Comment by Vitalini** [comment]
I think that the button under the UITableViewControllers, how to set it's over (maybe z-index or something similar)?

**Comment by Vitalini** [comment]
I did it, I created the table programmatically. But now when you click the table disappears...

**Comment by lourenco-marinho** [comment]
@Vitalini you can try to debug your view hierarchy in Xcode  to find out the problem

**Comment by diogo10** [comment]
Some solution? I faced that too

**Comment by lourenco-marinho** [comment]
Hi @diogo10

try adding the button not into a UITableViewController and instead add it to a UIView, this way i think everything will be alright.

**Comment by diogo10** [comment]
Hum...Ok. I saw another issue with it. I will try. thanks.
