### ISSUE TITLE
UITableViewController initialization(?)

### ISSUE THREAD

**Issue by HackShitUp** [lourenco-marinho/ActionButton#31]
I don't know if this is possible, but is there a way to show this on top of a UITableViewController? I have a TabBarController that holds around 3 UITableViewControllers, and 2 UICollectionViewControllers. Is there a way to initialize this on any one of them? This is awesome btw.

**Comment by HackShitUp** [comment]
Nevermind, got it. Just attach the view to UIApplication.sharedApplication().
Thanks!!!

**Comment by a75c6** [comment]
@HackShitUp Do you have an example of how you did this?
