### ISSUE TITLE
iOS 7 compatibility

### ISSUE THREAD

**Issue by guilhermearaujo** [lourenco-marinho/ActionButton#4]
Any chance of making iOS 7 compatible, even if dropping the blur effect support?

**Comment by lourenco-marinho** [comment]
Hi, @guilhermearaujo! We can create a new branch that is iOS 7 compatible to implements this. I still have some other priorities over this issue but it would be great to have your help :D

**Comment by guilhermearaujo** [comment]
I'm trying to make it work, but on iOS 7, when the menu button will rotate, its center strangely changes moves up and left. I'm not fully sure, but I suspect it is due autolayout/VFL. Since the button's frame size increases (by sqrt(2) when rotating 45º), it has to be pushed away from the screen margins to keep the same 15 dp margin. However iOS 8 seems to be smarter and ignores it.

**Comment by lourenco-marinho** [comment]
I'll be looking to this problem and keep you posted on any changes.

Thanks!

**Comment by lourenco-marinho** [comment]
Hi @guilhermearaujo i've been looking this issue and after some research maybe the problem is that the `anchorPoint` and `position` is not being set on the button's layer. Somehow iOS 8 seems to set it automatically.
