### ISSUE TITLE
toggle menu

### ISSUE THREAD

**Issue by mkchoi212** [lourenco-marinho/ActionButton#5]
How would I make it so that the menu toggles once the label has been pressed? The label and the toggle menu are in separate classes so I couldn't think of anything else other than using nsnotification

**Comment by lourenco-marinho** [comment]
Hi @mkchoi212 you can capture the action instance in the scope of the ActionButtonItem action closure and call toogleMenu().

`let email = ActionButtonItem(title: "email", image: emailImage)`
`email.action = { item in actionButton.toogleMenu() }`

I'll be working on a fix for this issue, but for now you can make it work like this.

Thanks :)

**Comment by mkchoi212** [comment]
Got it, thanks!
