### ISSUE TITLE
App crashes when tap button

### ISSUE THREAD

**Issue by krishnaverma** [lourenco-marinho/ActionButton#6]
the app is constantly getting crashed when I tap the action button with error EXE_BAD_ACCESS could you please help what is causing is?

**Comment by lourenco-marinho** [comment]
Hi @krishnaverma maybe it's because you're releasing the button when its action is called. Try declaring the ActionButton as a property of your class, this way you willl have a strong reference to the ActionButton.

Hope this help :)

**Comment by krishnaverma** [comment]
Exactly same issue was that I just declared variable in viewDidLoad.Thanx @lourenco-marinho thanx for sharing such a wonderful stuff.

**Comment by lourenco-marinho** [comment]
I'm glad to help @krishnaverma and spread the word about ActionButton ;D

Thanks!
