### ISSUE TITLE
can i go to another screen by taping the + button?

### ISSUE THREAD

**Issue by yonidaniel** [lourenco-marinho/ActionButton#7]
First thing you have done an amazing job - thank you very much! Secondly, I wanted to know if we can add a transition between screens when you press the button (+) not on Google and Twitter. I know that the class is NSObject and not UIButton, and that can create problems with the method "touchesBegan: withEvent:" and with "Prepareforsegue" 
In simple terms, I want to press the button and it will take me to another screen
tnx :+1:

**Comment by lourenco-marinho** [comment]
Hi @yonidaniel! Thanks for your comment :)

If you're attaching the button to a UIViewController's view you can just call 'self.performSegueWithIdentifier' from your view controller, inside the button's actions.

I hope that helps
